---
title: ElasticSearch internals monitoring by Zabbix (v2 traps)
date: '2014-12-06T14:41:00.004+03:00'
tags:
- linux
- zabbix
modified: '2015-01-07T19:11:27.240+03:00'
thumbnail: /assets/img/2014/e1.png
url: /2014/12/elasticsearch-internals-monitoring-by.html
---
Here is more resource oriented version of ElasticSearch monitoring from [previous article](/2014/02/elasticsearch-internals-monitoring-by.html) with using zabbix-traps. Also, it comes with very basic template, which was so asked in comments:
![](/assets/img/2014/e1.png)
Graphs included:
- Shard's nodes status
- Indices tasks speed
- Indices tasks time spend

Installation:
1. Save this as `/etc/zabbix/zabbix_agentd.d/elasticsearch.conf`:
```bash
#Key jvm.uptime_in_millis used to trigger trap sending
UserParameter=es[*],/etc/zabbix/elasticsearch.py $1
```
1. And here is the data-getter:  
[/etc/zabbix/elasticsearch.py](https://github.com/sepich/zabbix/raw/master/elasticsearch.py)
2. Then import template:
[template_app_elasticsearch.xml](https://github.com/sepich/zabbix/raw/master/templates/template_app_elasticsearch.xml)

How to add a new counter:
- Browse JSON output of your server's:
`curl http://localhost:9200/_nodes/_local/stats?all=true`
- Write path to value of interest using dot as separator, for example:  
`indices.docs.count`
- Create new counter in zabbix with:   
`key name = es[path.you.found]`  
and `type = zabbix_trap`

And here is the difference from [previous version](/2014/02/elasticsearch-internals-monitoring-by.html):   
Please note that you also need to add this path to counter to traps2 section of `elasticsearch.py` file. Then execute `elasticsearch.py` without any parameters and debug of `zabbix_sender` should be written to console. In top section you should find your new counter key (if it isn't - key is not found or empty in JSON output), and in bottom section number of failed items should be zero (if it isn't - there is no such key for this server configured in zabbix web)

Comments imported from blogger:
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-01-05T11:11:16.882+03:00">11:11, 05 January 2015</time>:<br/>
Hi, Can you please add the steps to monitor another host instead of localhost .<br />if i want to monitor like 10.0.1.10 host from my zabbix server 10.0.1.5, so what steps i need to do on remote host and zabbix server as well.</div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-01-05T11:28:42.654+03:00">11:28, 05 January 2015</time>:<br/>
Just a usual monitoring of remote host by zabbix-agent. Something like this:<br />- install zabbix-agent on remote host<br />- add this host to zabbix-server, add it to some &quot;generic linux template&quot;  and check that basic data started to collect (zabbix-agent must return the same &quot;hostname&quot; as it is configured for this host on zabbix-server side)<br />- then proceed with expanding data with elasticsearch checks - import template from this article on zabbix-server side, and add it to your host<br />- on host side configure<br />/etc/zabbix/zabbix_agentd.d/elasticsearch.conf and<br />/etc/zabbix/elasticsearch.py<br /><br />So, the template should be installed only once on server side, and then assigned to hosts needed. But config for agent-check and script to collect the data should be installed on each elasticsearch host (and they are sending data about localhost back to zabbix-server)</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/04123622521578387688">Unknown</a> at <time datetime="2015-01-07T19:08:54.507+03:00">19:08, 07 January 2015</time>:<br/>
when I run script I get this error:<br /><br /> 12539:20150107:102815.007 item &quot;nw-esclient-201.prod.pcln.com:es[jvm.uptime_in_millis]&quot; became not supported: Received value [File &quot;/usr/local/zabbix/bin/elasticsearch.py&quot;, line 22    &quot;status&quot;,            ^SyntaxError: invalid syntax] is not suitable for value type [Numeric (float)]<br /></div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-01-07T19:23:08.929+03:00">19:23, 07 January 2015</time>:<br/>
Maybe there is some EOL issue when you&#39;d downloaded the script?<br />What is shown when you try:<br /># python elasticsearch.py<br />?</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/04123622521578387688">Unknown</a> at <time datetime="2015-01-07T19:31:26.936+03:00">19:31, 07 January 2015</time>:<br/>
bash-4.1$ python elasticsearch.py<br />  File &quot;elasticsearch.py&quot;, line 22<br />    &quot;status&quot;,<br />            ^<br />SyntaxError: invalid syntax<br /></div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-01-07T19:40:26.201+03:00">19:40, 07 January 2015</time>:<br/>
Dunno, syntax looks valid. At least for python2 i have installed at my home box (there is no elasticsearch)<br /># wget https://github.com/sepich/zabbix/raw/master/elasticsearch.py &amp;&gt;/dev/null<br /># python elasticsearch.py<br />Unable to load JSON data!<br /><br />So, no any syntax errors. What&#39;s your OS and python?</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/04123622521578387688">Unknown</a> at <time datetime="2015-01-07T19:47:41.115+03:00">19:47, 07 January 2015</time>:<br/>
Thanks for helping out, OS=Red Hat Enterprise Linux Server release 6.5 <br />with Python 2.6.6</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/02923388877084893061">Unknown</a> at <time datetime="2015-01-12T15:21:51.472+03:00">15:21, 12 January 2015</time>:<br/>
Hi Tom,<br />add None value to all keys in traps1 and traps2 dictionaries<br /><br />ie. (line 22) &quot;status&quot;: None,<br /><br />Worked for me on same environment</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/04123622521578387688">Unknown</a> at <time datetime="2015-01-14T19:51:43.948+03:00">19:51, 14 January 2015</time>:<br/>
Thanks Federico, that helped:<br /><br />bash-4.1$ ./elasticsearch.py jvm.uptime_in_millis<br />10116541216<br /><br />But this errors:<br /><br />bash-4.1$ ./elasticsearch.py jvm_heap_p_used<br />zabbix_sender [18783]: Warning: [line 1] &#39;-&#39; encountered as &#39;Hostname&#39;, but no default hostname was specified<br />Sending failed.<br /></div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-01-21T19:41:14.623+03:00">19:41, 21 January 2015</time>:<br/>
Hi,<br />Can you help me:<br /><br />Traceback (most recent call last):<br />  File &quot;./elasticsearch.py&quot;, line 70, in <br />    main()<br />  File &quot;./elasticsearch.py&quot;, line 64, in main<br />    stats=stats[c.pop(0)]<br />UnboundLocalError: local variable &#39;stats&#39; referenced before assignment</div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-01-21T22:26:29.103+03:00">22:26, 21 January 2015</time>:<br/>
There is no such code (stats=stats[c.pop(0)]) anywhere in file:<br />https://github.com/sepich/zabbix/blob/master/elasticsearch.py<br />Maybe you are trying with some older version?<br />Could you try with the latest?</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-03-04T16:10:08.802+03:00">16:10, 04 March 2015</time>:<br/>
Hi There,<br /><br />This is a great solution, thank you for sharing. I have a small problem with it. elasticsearch.py script runs OK on my other nodes but on my master node, it returns &quot;Unable to load JSON data!&quot; error. I don&#39;t know python therefore cannot really figure out what the code does but I assume something fails here:<br /><br />for node_id in all[&#39;nodes&#39;]:<br />      if all[&#39;nodes&#39;][node_id][&#39;host&#39;].startswith(os.uname()[1]):<br />        node = all[&#39;nodes&#39;][node_id]<br />        if len(sys.argv) == 1:<br />          print &quot;node found&quot;<br />  except:<br />    print &quot;Unable to load JSON data!&quot;<br />    sys.exit(1)<br /><br />Any ideas?</div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-03-04T17:33:16.955+03:00">17:33, 04 March 2015</time>:<br/>
Looks like cluster node name differs from hostname on that server. Tell me what are they and I&#39;ll think how script should be modified to handle this</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-03-05T11:50:24.044+03:00">11:50, 05 March 2015</time>:<br/>
Hmm, that&#39;s strange :) I have the same naming convention on all nodes.<br />hostnames: eslog001.abc.local to eslog005.abc.local (first one is the master and the problem is there)<br />Node names: ES_ONE, ES_TWO, ES_THREE, ES_FOUR, ES_FIVE</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-03-09T18:00:22.981+03:00">18:00, 09 March 2015</time>:<br/>
I don&#39;t know if you got the reply, if not, let me know and I&#39;ll send it again.</div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-03-09T18:27:31.381+03:00">18:27, 09 March 2015</time>:<br/>
In this case it should not work on other nodes too ;)<br />if all[&#39;nodes&#39;][node_id][&#39;host&#39;].startswith(os.uname()[1]):<br />Basically what this code does - it search all cluster nodes looking for that which starts with current hostname. So, for eslog001.abc.local hostname would be eslog001.<br />If your cluster nodes names are not equal to hostnames - you can just hardcode it in script like this:<br />if all[&#39;nodes&#39;][node_id][&#39;host&#39;].startswith(&#39;ES_ONE&#39;):<br /></div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-03-10T11:34:41.519+03:00">11:34, 10 March 2015</time>:<br/>
This is really strange. I have created a script as you advised with the hard coded node address and hard coded node name. It still does not work on the problematic server (unable to load JSON) but if I run the exact same script on others with the problematic server&#39;s address and name hardcoded, it works :)</div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-03-14T21:59:42.669+03:00">21:59, 14 March 2015</time>:<br/>
Actually python scripts are not so hard in debugging<br />Just open python prompt:<br /># python<br />And then copy-paste everything from script which is above <br />def main():<br />line (actually only imports and getKeys needed here). Then copy-paste beginning of main():<br />    f = requests.get(&quot;http://localhost:9200/_cluster/health&quot;)<br />    health = f.json()<br />    f = requests.get(&quot;http://localhost:9200/_nodes/_local/stats?all=true&quot;)<br />    all = f.json()<br />Now we are coming to problem place. Let&#39;s check what nodes are exist in health report:<br />&gt;&gt;&gt; for node_id in all[&#39;nodes&#39;]: print all[&#39;nodes&#39;][node_id][&#39;host&#39;]<br />there should be all nodes names printed out. And we looking here for current server, with this name:<br />&gt;&gt;&gt; print os.uname()[1]<br />Do you see some node in previous output with name starting with exact same characters?<br /><br />Oh, I&#39;ve remember that error was &quot;Unable to load JSON data!&quot;, so it is exception during one of those commands execution. When you did copy-paste lines from script - where do you saw errors?</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-03-19T19:52:38.426+03:00">19:52, 19 March 2015</time>:<br/>
Hi<br /><br />I have tried using this script but keep getting this error when I run it:<br /><br />  File &quot;/etc/zabbix/elasticsearch.py&quot;, line 22<br />    &quot;status&quot;,<br />            ^<br />SyntaxError: invalid syntax<br /></div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/13132519644373590143">humit</a> at <time datetime="2015-06-24T16:56:02.220+03:00">16:56, 24 June 2015</time>:<br/>
Hi all,<br /><br />If you receive the error &quot;Unable to load JSON data!&quot; try running the command: <br /><br />curl -XGET &#39;http://localhost:9200/_cluster/health&#39; <br /><br />In my case, the elasticsearch process was not listening on localhost (127.0.0.1) and I got the error:<br /><br />curl: (7) couldn&#39;t connect to host<br /><br />Then making a &quot;sudo netstat -ntlp&quot; revealed the IP address and port elasticsearch is listening to and replacing &quot;localhost&quot; with this IP address in the script solved the problem.</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-08-04T16:20:25.084+03:00">16:20, 04 August 2015</time>:<br/>
zabbix_sender [6743]: DEBUG: answer [{&quot;response&quot;:&quot;success&quot;,&quot;info&quot;:&quot;processed: 0; failed: 33; total: 33; seconds spent: 0.000243&quot;}]<br />info from server: &quot;processed: 0; failed: 33; total: 33; seconds spent: 0.000243&quot;<br />sent: 33; skipped: 0; total: 33</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/09713939352011386209">Unknown</a> at <time datetime="2015-08-21T09:47:38.916+03:00">09:47, 21 August 2015</time>:<br/>
incorrect settings zabbiks-agent?</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-08-29T03:33:32.675+03:00">03:33, 29 August 2015</time>:<br/>
I hardcoded my hostname<br />line 71<br />    out += &quot;YOURHOSTNAMEHERE es.{0} {1}\n&quot;.format(t,s)</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-10-05T19:58:37.028+03:00">19:58, 05 October 2015</time>:<br/>
Hello.<br />I performed the process but do not have the /etc/zabbix/zabbix_agendtd.d directory, just /etc/zabbix/agentd_conf.d.<br />Use version 2.4 of zabbix, but monitoring is not bringing any results.<br /><br />Can you help me?</div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-10-05T20:03:28.477+03:00">20:03, 05 October 2015</time>:<br/>
Sure, you need to use &#39;/etc/zabbix/agentd_conf.d&#39; folder if it is in your /etc/zabbix/zabbix_agent.conf &#39;Include&#39; statement</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-10-05T20:31:13.337+03:00">20:31, 05 October 2015</time>:<br/>
Tks for your fast reply.<br /><br />Look that:<br />/etc/zabbix/zabbix_agentd.conf, is all right.<br /><br />### Option: Include<br />#       You may include individual files or all files in a directory in the configuration file.<br />#       Installing Zabbix will create include directory in /etc/zabbix, unless modified during the compile time.<br /># <br /># Mandatory: no<br /># Default:<br /># Include=<br /># Include=/etc/zabbix/zabbix_agentd.userparams.conf<br /># Include=/etc/zabbix/zabbix_agentd.conf.d/<br />Include=/etc/zabbix/zabbix_agentd.conf.d/<br /><br /><br /><br /><br />I also changed the /etc/zabbix/elasticsearch.py <br /><br />cfg = &#39;/etc/zabbix/zabbix_agentd.conf.d&#39; # path to zabbix-agent config<br /><br /><br />Nothing ocurrs</div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-10-05T23:07:20.611+03:00">23:07, 05 October 2015</time>:<br/>
Did you tried to run:<br /># /etc/zabbix/elasticsearch.py <br />Did you tried to run:<br /># zabbix_agentd -k &#39;es[indices.docs.count]&#39;<br />What are the results?</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">David Lang</a> at <time datetime="2015-10-05T23:48:57.321+03:00">23:48, 05 October 2015</time>:<br/>
one bug, it doesn&#39;t find the node if the case is difference between the hostname and the node name, inserting a couple of .lower() into the comparison fixes that<br /><br />I also think it&#39;s a good idea to modify line 72 to be:<br /><br />    out += &quot;{0} es.{1} {2}\n&quot;.format(os.uname()[1],t,s)<br /></div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-10-06T16:18:19.686+03:00">16:18, 06 October 2015</time>:<br/>
Runnig /etc/zabbix/elasticsearch.py, nothing occurs.<br /><br />The other command return these result:<br /><br />aryel@backend-elasticsearch-dev-data-igm-pri-instance-l7d5:/usr/sbin$ ./zabbix_agentd -t &#39;es[indices.docs.count]&#39;<br />es[indices.docs.count]                        [m|ZBX_NOTSUPPORTED]</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-10-06T16:20:25.780+03:00">16:20, 06 October 2015</time>:<br/>
Retrying the command:<br /><br />- es.status 503<br />- es.indices.search.fetch_total 0<br />- es.indices.merges.total 11950<br />- es.indices.refresh.total_time_in_millis 1394850<br />- es.indices.indexing.index_time_in_millis 372322<br />- es.os.mem.actual_used_in_bytes 3064516608<br />- es.indices.merges.total_time_in_millis 3231557<br />- es.indices.flush.total 253<br />- es.indices.indexing.index_total 328279<br />- es.indices.indexing.delete_total 0<br />- es.indices.docs.deleted 0<br />- es.jvm.mem.heap_committed_in_bytes 3203792896<br />- es.indices.indexing.delete_time_in_millis 0<br />- es.indices.get.missing_total 0<br />- es.indices.search.query_time_in_millis 0<br />- es.indices.get.exists_time_in_millis 0<br />- es.indices.search.fetch_time_in_millis 0<br />- es.indices.search.query_total 0<br />- es.indices.docs.count 573692<br />- es.jvm.mem.heap_used_in_bytes 756227784<br />- es.indices.refresh.total 108393<br />- es.indices.store.throttle_time_in_millis 25133<br />- es.indices.warmer.total_time_in_millis 1250<br />- es.indices.get.exists_total 0<br />- es.indices.get.missing_time_in_millis 0<br />- es.indices.flush.total_time_in_millis 15132<br />- es.os.mem.actual_free_in_bytes 4799635456<br />- es.indices.warmer.total 5491</div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-10-06T22:52:30.984+03:00">22:52, 06 October 2015</time>:<br/>
ZBX_NOTSUPPORTED - means zabbix agent does not know what &#39;es[]&#39; item key mean. Agent should be restarted after you put config file in place.<br />- es.indices.merges.total 11950 ... - means data is collecting ok.</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-10-07T19:14:35.586+03:00">19:14, 07 October 2015</time>:<br/>
I reinstall the agent, but anything still wrong<br />Could you help me?<br />aryel@backend-elasticsearch-dev-data-igm-pri-instance-l7d5:/etc/zabbix$ ./elasticsearch.py <br />node found<br />- es.status yellow<br />- es.unassigned_shards 0<br />- es.active_primary_shards 10<br />- es.initializing_shards 1<br />- es.active_shards 19<br />- es.relocating_shards 0<br />- es.indices.search.fetch_total 0<br />- es.indices.merges.total 13889<br />- es.indices.refresh.total_time_in_millis 1618108<br />- es.indices.indexing.index_time_in_millis 441191<br />- es.os.mem.actual_used_in_bytes 3084935168<br />- es.indices.merges.total_time_in_millis 3596862<br />- es.indices.flush.total 311<br />- es.indices.indexing.index_total 395003<br />- es.indices.indexing.delete_total 0<br />- es.indices.docs.deleted 0<br />- es.jvm.mem.heap_committed_in_bytes 3203792896<br />- es.indices.indexing.delete_time_in_millis 0<br />- es.indices.get.missing_total 0<br />- es.indices.search.query_time_in_millis 0<br />- es.indices.get.exists_time_in_millis 0<br />- es.indices.search.fetch_time_in_millis 0<br />- es.indices.search.query_total 0<br />- es.indices.docs.count 401643<br />- es.jvm.mem.heap_used_in_bytes 1063793304<br />- es.indices.refresh.total 124231<br />- es.indices.store.throttle_time_in_millis 94<br />- es.indices.warmer.total_time_in_millis 2<br />- es.indices.get.exists_total 0<br />- es.indices.get.missing_time_in_millis 0<br />- es.indices.flush.total_time_in_millis 17301<br />- es.os.mem.actual_free_in_bytes 4779216896<br />- es.indices.warmer.total 19<br />zabbix_sender [2106]: DEBUG: answer [{&quot;response&quot;:&quot;success&quot;,&quot;info&quot;:&quot;processed: 0; failed: 33; total: 33; seconds <br />spent: 0.000331&quot;}]<br />info from server: &quot;processed: 0; failed: 33; total: 33; seconds spent: 0.000331&quot;<br />sent: 33; skipped: 0; total: 33</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/17613053558958470481">Alper</a> at <time datetime="2015-11-13T11:38:58.807+03:00">11:38, 13 November 2015</time>:<br/>
Hi there, I had elasticsearch 1.5 and this script was working like a charm but after update to elasticsearch 2.0 it stopped working and giving this error:<br /><br />Traceback (most recent call last):<br />  File &quot;/etc/zabbix/elasticsearch.py&quot;, line 117, in <br />    main()<br />  File &quot;/etc/zabbix/elasticsearch.py&quot;, line 94, in main<br />    out += getKeys(node,traps2)    #getting stats  values<br />UnboundLocalError: local variable &#39;node&#39; referenced before assignment<br /><br />I don&#39;t see any difference in the output of http://localhost:9200/_nodes/_local/stats?all=true<br />Any idea?<br /></div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/17613053558958470481">Alper</a> at <time datetime="2015-11-13T17:54:55.995+03:00">17:54, 13 November 2015</time>:<br/>
I&#39;ve found the issue. Previously I was using hostnames now I am using IP addresses. I forgot to change this in the script. :)</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/03629058230979337980">Unknown</a> at <time datetime="2015-11-18T16:51:50.874+03:00">16:51, 18 November 2015</time>:<br/>
Having a problem.<br /><br />If i run the script directly as root or zabbix (with shell)<br /><br />./elasticsearch.py `hostname`<br />: No such file or directory<br /><br />or ./elasticsearch.py<br />: No such file or directory<br /><br />If I run it as python ./elasticsearch.py it procudes the output fine.<br /><br />suggestions<br /></div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2015-11-19T19:29:58.045+03:00">19:29, 19 November 2015</time>:<br/>
if I run it manually just once the graphs build without issue, so added a cronjob to give it a kick<br /><br />I still dont understand exactly why this is.</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/03072131531120012795">Unknown</a> at <time datetime="2015-11-25T14:58:00.375+03:00">14:58, 25 November 2015</time>:<br/>
Please consider Elasticsearch 2.0 compatibility patch:<br />https://github.com/islepnev/zabbix/commit/f413717ce5c3a4b9ead0c8f417a2ba2a53<br />6b78d9</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/03072131531120012795">Unknown</a> at <time datetime="2015-11-25T15:04:15.437+03:00">15:04, 25 November 2015</time>:<br/>
Please consider Elasticsearch 2.x compatibility patch:<br /><br />https://github.com/islepnev/zabbix/commit/f413717ce5c3a4b9ead0c8f417a2ba2a536b78d9</div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-11-25T22:00:30.147+03:00">22:00, 25 November 2015</time>:<br/>
Thank you</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/07235517524883934703">Unknown</a> at <time datetime="2015-12-26T22:37:18.914+03:00">22:37, 26 December 2015</time>:<br/>
Dear Sepa, please explain how do you make your script send traps periodically? It works fine once, but then nothing happens. Do you use cron to schedule it?</div>
<div class="comment"><img src="//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPIpsFZxeXhwYiaSZFfaBPHaq47D5RjLrUTuKOI_W56xwu2EUEm5gpwBmn6mTlXeSGQMaEmVd4aZENpSrUZQxNXaELJA-QehvcCmMPoa7dXhqdTPW34s6syA1ZCo6yvsI/s1600/avatar.png"/><a href="https://www.blogger.com/profile/15219082553292373774">sepa</a> at <time datetime="2015-12-26T22:44:26.510+03:00">22:44, 26 December 2015</time>:<br/>
There is one &#39;active check&#39; which is sending traps when it is requested by agent. You see there is even note about it in elasticsearch.conf:<br />#Key jvm.uptime_in_millis used to trigger trap sending<br />So you can tune time period for this active check to also change period when traps are send.</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/07235517524883934703">Unknown</a> at <time datetime="2015-12-27T01:56:11.698+03:00">01:56, 27 December 2015</time>:<br/>
I didn&#39;t get sorry, <br />I put<br />sudo zabbix_agentd -t &#39;es[jvm.uptime_in_millis]&#39;<br />and get<br />elasticsearch% sudo zabbix_agentd -t &#39;es[jvm.uptime_in_millis]&#39;<br />es[jvm.uptime_in_millis]                      [t|8242898]<br /><br />and that&#39;s all, zabbix_agentd doesn&#39;t start with this parametr</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/07235517524883934703">Unknown</a> at <time datetime="2015-12-27T03:08:15.253+03:00">03:08, 27 December 2015</time>:<br/>
Well, finally I get the thing. I added jvm.uptime_in_millis param to trap list that is sended to server in .py file and set time period for this trap, which is actually Zabbix agent (active)</div>
<div class="comment"><img src="//www.blogger.com/img/blogger_logo_round_35.png"/><a href="https://www.blogger.com/profile/08436052813675777866">cookies</a> at <time datetime="2016-05-18T20:34:40.993+03:00">20:34, 18 May 2016</time>:<br/>
Hi, can you give me some more hints about this, please? I added to traps:<br /><br />out += &quot;- {0} {1}\n&quot;.format(&quot;es[jvm.uptime_in_millis]&quot;,&quot;5000&quot;)<br /><br /><br />but I still don&#39;t get how this is supposed to work.</div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2016-06-08T06:13:56.509+03:00">06:13, 08 June 2016</time>:<br/>
So i have tried, lets call it option 1<br /><br />  &quot;jvm.mem.heap_used_in_bytes&quot;,<br />  &quot;os.mem.actual_free_in_bytes&quot;,<br />  &quot;os.mem.actual_used_in_bytes&quot;,<br />  &quot;jvm.uptime_in_millis&quot;,<br /><br /><br />and this option 2<br /><br />  &quot;jvm.mem.heap_used_in_bytes&quot;,<br />  &quot;os.mem.actual_free_in_bytes&quot;,<br />  &quot;os.mem.actual_used_in_bytes&quot;,<br />  &quot;es[jvm.uptime_in_millis]&quot;,<br /><br />Changed the key on the Zabbix server to match both the above. <br /><br />Get this if i use the first option i try <br />zabbix_sender [21571]: DEBUG: answer [{&quot;response&quot;:&quot;success&quot;,&quot;info&quot;:&quot;processed: 33; failed: 1; total: 34; seconds spent: 0.000328&quot;}]<br />info from server: &quot;processed: 33; failed: 1; total: 34; seconds spent: 0.000328&quot;<br />sent: 34; skipped: 0; total: 34<br /><br />I get this result on option 2<br /><br />zabbix_sender [19248]: DEBUG: answer [{&quot;response&quot;:&quot;success&quot;,&quot;info&quot;:&quot;processed: 33; failed: 0; total: 33; seconds spent: 0.000305&quot;}]<br />info from server: &quot;processed: 33; failed: 0; total: 33; seconds spent: 0.000305&quot;<br />sent: 33; skipped: 0; total: 33<br /><br />for the life of me i cant get it to update the trap stats automatically, does a great job if I run the script manually.<br /><br />is there a bug somewhere?<br /><br /><br /></div>
<div class="comment"><img src="//resources.blogblog.com/img/blank.gif"/><a href="#">Anonymous</a> at <time datetime="2016-08-23T15:36:07.629+03:00">15:36, 23 August 2016</time>:<br/>
Hi,<br />i am struggeling with the elasticsearch.py.<br />Everything works well since month with RHEL6.4, zabbix 2.4 client; Java 1.7 and Elasticsearch 1.2.4<br />Now we upgrade and have RHEL6.7, zabbix Client 3.0.4, Java 1.8 and ES 2.1.2<br />In this new enviroment elasticsearch.py does not return any info when startet from the commandline. It does in the old enviroment. Do you have any idear what i can do to get this working?<br /></div>
